language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -q twisted --use-mirrors
  - pip install -q twistedhttpstream --use-mirrors
  - pip install -q requests --use-mirrors
  - pip install -q sympy --use-mirrors
  - pip install -q mocker --use-mirrors
  - pip install -q Markdown --use-mirrors
  - pip install -q PyYAML --use-mirrors
  - pip install -q pyOpenSSL --use-mirrors
  - pip install -q python-flowdock --use-mirrors


# command to run tests
script: source ~/virtualenv/python2.7/bin/activate && python tests.py