services:
    shirka.bot:
        class: shirka.consumers.Bot
        arguments: [ '%shirka.bot.name%', '%shirka.bot.email%', '%shirka.bot.url%']
        kwargs:
            process_executor: '@shirka.process.executor'

    shirka.process.executor:
        class: shirka.tools.process.ProcessExecutor
        arguments:
            - '%shirka.data.dir%/proc'
            
    shirka.flask.view.shirka_proc_list:
        class: [shirka.control.proc, ProcListView.as_view]
        arguments: 
            - shirka_proc_list
            - "%shirka.data.dir%/proc"

    shirka.flask.view.shirka_proc_view:
        class: [shirka.control.proc, ProcView.as_view]
        arguments: 
            - shirka_proc_view
            - "%shirka.data.dir%/proc"

    shirka.flask.view.shirka_proc_read_view:
        class: [shirka.control.proc, ProcReadView.as_view]
        arguments: 
            - shirka_proc_read_view
            - "%shirka.data.dir%/proc"

    shirka.twisted.web.resource:
        class: twisted.web.resource.Resource
        calls:
            - [putChild, ['public', '@shirka.twisted.web.resource.static']]
            - [putChild, ['api', '@shirka.twisted.web.resource.wsgi']]

    shirka.twisted.web.resource.static:
        class: twisted.web.static.File
        arguments: 
            - '%shirka.web.public.dir%'

    shirka.twisted.web.resource.wsgi:
        class: twisted.web.wsgi.WSGIResource
        arguments: 
            - '@ioc.extra.twisted.reactor'
            - '@ioc.extra.twisted.reactor.thread_pool'
            - '@ioc.extra.flask.app'

    shirka.twisted.web.site:
        class: twisted.web.server.Site
        arguments: 
            - '#@shirka.twisted.web.resource'

    shirka.tools.paramiko:
        class: shirka.tools.paramiko.Paramiko